FROM debian:bookworm-slim
WORKDIR /usr/src

ENV PULSE_SERVER=tcp:audio:4317
ENV PULSE_SOURCE=snapcast.monitor

RUN apt-get update && apt-get install -y --no-install-recommends \
    snapserver \
    libpulse0 \
    libasound2-plugins \
    curl \
    iproute2 \
  && rm -rf /var/lib/apt/lists/*

COPY snapserver.conf /etc/snapserver.conf
COPY start.sh .

CMD [ "/bin/bash", "/usr/src/start.sh" ]
