wireplumber.components = [
  {
    name = balena-play-detect.lua
    type = script/lua
    provides = custom.balena-play-detect
  }
]

wireplumber.profiles = {
  main = {
    custom.balena-play-detect = required
  }
}
